language: cpp

env:
  global:
    - LINUX_DIST=trusty
    - DEPS_DIR=${TRAVIS_BUILD_DIR}/deps
    - CXX_FLAGS="-Wall -Werror"
    - RUN_TESTS=true
    - COVERAGE=false

matrix:
  inlcude:
    - compiler: gcc
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-6
          - valgrind
          - lcov
          - libgtest-dev
      env: COMPILER=g++-6

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libgtest-dev valgrind cmake
  - cd /usr/src/gtest
  - sudo cmake CMakeLists.txt
  - sudo make 
  - sudo cp *.a /usr/lib
  - cd "{TRAVIS_BUILD_DIR}" 

install:
  - sudo pip install codeconv
  - |
    if [[ ${TRAVIS_OS_NAME} == "linux" ]]; then
      CMAKE_URL="http://www.cmake.org/files/v3.5/cmake-3.5.1-Linux-x86_64.tar.gz"
      mkdir -p ${DEPS_DIR}/cmake
      travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C ${DEPS_DIR}/cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    fi
  - echo ${PATH}
  - echo ${CXX}
  - ${CXX} --version
  - ${CXX} -v
  - cmake --version

script:
  - mkdir build
  - cd build
  - cmake ${CMAKE_OPTIONS} -DCMAKE_CXX_FLAGS=${CXX_FLAGS} -DCMAKE_CXX_COMPILER=$COMPILER -DCMAKE_BUILD_TYPE=ON -DBUILD_TESTS=ON .. && make
